nao_app_homepage:
    path:     /
    defaults: { _controller: NAOAppBundle:Home:index }

nao_app_adminpage:
    path:     /admin
    defaults: { _controller: NAOAppBundle:Admin:index }

nao_app_user_management:
    path:     /admin/gestion-des-utilisateurs
    defaults: { _controller: NAOAppBundle:Admin:userManagement }

nao_app_user_delete:
    path:     /admin/gestion-des-utilisateurs/supprimer/{id}
    defaults: { _controller: NAOAppBundle:Admin:delete }
    requirements:
        id:   \d+

nao_app_user_promote:
    path:     /admin/gestion-des-utilisateurs/promouvoir/{id}
    defaults: { _controller: NAOAppBundle:Admin:promote }
    requirements:
        id:   \d+

nao_app_user_demote:
    path:     /admin/gestion-des-utilisateurs/retrograder/{id}
    defaults: { _controller: NAOAppBundle:Admin:demote }
    requirements:
        id:   \d+