nao_app:
    resource: "@NAOAppBundle/Resources/config/routing.yml"
    prefix:   /

nao_user:
    resource: "@NAOUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
